# Generated by Django 5.2.7 on 2026-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('compteur', models.IntegerField()),
                ('temperature_max', models.FloatField()),
                ('op1_ack', models.BooleanField(default=False)),
                ('op1_comment', models.TextField(blank=True)),
                ('op2_ack', models.BooleanField(default=False)),
                ('op2_comment', models.TextField(blank=True)),
                ('op3_ack', models.BooleanField(default=False)),
                ('op3_comment', models.TextField(blank=True)),
            ],
        ),
    ]
