# Generated by Django 5.2.7 on 2026-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='temperature_max',
            new_name='max_temperature',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='date_fin',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='compteur',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='date_debut',
        ),
        migrations.AddField(
            model_name='incident',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
