# Generated by Django 5.2.7 on 2026-01-10 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_rename_temperature_max_incident_max_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='start_date',
        ),
        migrations.AddField(
            model_name='incident',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
